fold: 4
defaults:
  - _self_
  - dataset_unsupervised/parquet_click
  - inference/inference_click
  - downstream/downstream
  
seed_everything: 42
logger_name: click_coles_${fold}
model_path: scenario_datafusion/models/${logger_name}.p
embed_file_name: ${logger_name}

data_module:
  _target_: ptls.frames.PtlsDataModule
  train_data:
    _target_: ptls.frames.coles.ColesIterableDataset
    col_time: click_event_time
    splitter:
      _target_: ptls.frames.coles.split_strategy.SampleSlices
      split_count: 5
      cnt_min: 32
      cnt_max: 180
    data: ${dataset_unsupervised.train}
  valid_data:
    _target_: ptls.frames.coles.ColesIterableDataset
    col_time: click_event_time
    splitter:
      _target_: ptls.frames.coles.split_strategy.SampleSlices
      split_count: 5
      cnt_min: 32
      cnt_max: 180
    data: ${dataset_unsupervised.valid}
  train_batch_size: 256
  train_num_workers: 16
  valid_batch_size: 256
  valid_num_workers: 16
  
trainer:
  accelerator: gpu
  max_epochs: 30
  limit_val_batches: 5000
  gradient_clip_val: 0.5
  deterministic: true
  checkpoints_every_n_val_epochs: 1
  fast_dev_run: false
  
pl_module:
  _target_: ptls.frames.coles.CoLESModule
  validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 4
    metric: cosine
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    trx_encoder:
      _target_: ptls.nn.TrxEncoder
      embeddings_noise: 0.003
      embeddings:
        cat_id:
          in: 400
          out: 64
        level_0:
          in: 400
          out: 16
        level_1:
          in: 400
          out: 8
        level_2:
          in: 400
          out: 4
        hour:
          in: 25
          out: 16
        weekday:
          in: 8
          out: 4
    type: gru
    hidden_size: 256
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.AdamW
    lr: 0.001
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 3
    gamma: 0.9025
