defaults:
  - _self_

col_id: user_id
target_col_names:
  - higher_education

logger_name:

late_fusion:
  train1_path:
  test1_path:

  train2_path:
  test2_path:


model:
    _target_: lightgbm.LGBMClassifier
    n_estimators: 500
    boosting_type: gbdt
    subsample: 0.5
    subsample_freq: 1
    learning_rate: 0.02
    feature_fraction: 0.75
    max_depth: 6
    lambda_l1: 1
    lambda_l2: 1
    min_data_in_leaf: 50
    random_state: 42
    n_jobs: 8
    verbose: -1

metric:
    _target_: sklearn.metrics.roc_auc_score
    _partial_: true
    
output: result_lf.csv