fold: 4

defaults:
  - _self_
  - dataset_unsupervised/multimodal_parquet

logger_name: matching_conf_${fold}

inference_run: false
downstream_run: false

trainer:
    max_epochs: 50
    accelerator: gpu
    enable_progress_bar: True
    gradient_clip_val: 0.5
    log_every_n_steps: 50
    limit_val_batches: 512

data_module:
  _target_: ptls.frames.PtlsDataModule
  train_data:
    _target_: modules.matching.MultiModalDiffSplitIterableDataset
    splitters:
        trx:
          _target_: ptls.frames.coles.split_strategy.SampleSlices
          split_count: 2
          cnt_min: 32
          cnt_max: 180
        click:
          _target_: ptls.frames.coles.split_strategy.SampleSlices
          split_count: 2
          cnt_min: 32
          cnt_max: 180
    data: ${dataset_unsupervised.train}
    source_features:
        trx:
            - mcc_code
            - currency_rk
            - transaction_amt
            - event_time
            - hour
            - weekday
        click:
            - cat_id
            - level_0
            - level_1
            - level_2
            - event_time
            - hour
            - weekday
    col_id: user_id
    col_time: event_time
    source_names:
        - trx
        - click
  valid_data:
    _target_: modules.matching.MultiModalDiffSplitIterableDataset
    splitters:
        trx:
          _target_: ptls.frames.coles.split_strategy.NoSplit
        click:
          _target_: ptls.frames.coles.split_strategy.NoSplit
    data: ${dataset_unsupervised.valid}
    source_features:
        trx:
            - mcc_code
            - currency_rk
            - transaction_amt
            - event_time
            - hour
            - weekday
        click:
            - cat_id
            - level_0
            - level_1
            - level_2
            - event_time
            - hour
            - weekday
    col_id: user_id
    col_time: event_time
    source_names:
        - trx
        - click
  train_batch_size: 256
  train_num_workers: 255
  valid_batch_size: 256
  valid_num_workers: 255

pl_module:
  _target_: modules.matching.M3CoLESModule
  validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 1
    metric: cosine
  head:
    _target_: ptls.nn.Head
    input_size: 128
    use_norm_encoder: True
    hidden_layers_sizes: 
      - 128
      - 128
    objective: "regression"
    num_classes: 128
  seq_encoders:
        trx:
          _target_: ptls.nn.RnnSeqEncoder
          trx_encoder:
            _target_: ptls.nn.TrxEncoder
            norm_embeddings: false
            embeddings_noise: 0.003
            embeddings:
              mcc_code:
                in: 350
                out: 64
              currency_rk:
                in: 10
                out: 4
              hour:
                in: 25
                out: 16
              weekday:
                in: 8
                out: 4
            numeric_values:
              transaction_amt: log
          type: gru
          hidden_size: 128
        click: 
          _target_: ptls.nn.RnnSeqEncoder
          trx_encoder:
            _target_: ptls.nn.TrxEncoder
            embeddings_noise: 0.003
            embeddings:
              cat_id:
                in: 400
                out: 64
              level_0:
                in: 400
                out: 16
              level_1:
                in: 400
                out: 8
              level_2:
                in: 400
                out: 4
              hour:
                in: 25
                out: 16
              weekday:
                in: 8
                out: 4
          type: gru
          hidden_size: 128
  loss:
    _target_: ptls.frames.coles.losses.SoftmaxLoss
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.AdamW
    lr: 0.001
    weight_decay: 1e-4
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 1
    gamma: 0.9