fold: 4
defaults:
  - _self_
  - dataset_unsupervised/parquet_tab_trx
  - inference/inference_tab_trx
  - downstream/downstream

seed_everything: 42
logger_name: trx_tabbert_${fold}
model_path: scenario_mbd/models/${logger_name}.p
embed_file_name: ${logger_name}

data_module:
  _target_: ptls.frames.PtlsDataModule
  train_data:
    _target_: ptls.frames.tabformer.TabformerIterableDataset
    data: ${dataset_unsupervised.train}
    max_len: 300
    min_len: 80
  valid_data:
    _target_: ptls.frames.tabformer.TabformerIterableDataset
    data: ${dataset_unsupervised.valid}
    max_len: 300
    min_len: 80
  train_batch_size: 512
  train_num_workers: 16
  valid_batch_size: 128
  valid_num_workers: 16
  fast_dev_run: false
  
trainer:
  gpus: 1
  auto_select_gpus: false
  limit_val_batches: 5000
  max_epochs: 15
  deterministic: true
  checkpoints_every_n_val_epochs: 1
  gradient_clip_val: 0.1
  fast_dev_run: false
  
pl_module:
  _target_: ptls.frames.tabformer.TabformerPretrainModule
  total_steps: 20000
  mask_prob: 0.2
  feature_encoder: 
    _target_: ptls.nn.TabFormerFeatureEncoder
    n_cols: 9
    emb_dim: 24
  seq_encoder:
    _target_: ptls.nn.TransformerEncoder
    n_heads: 2
    n_layers: 2
    input_size: 216
    use_positional_encoding: false
  trx_encoder:
    _target_: ptls.nn.TrxEncoder
    norm_embeddings: false
    embeddings_noise: 0.003
    embeddings:
        event_type: 
            in: 59
            out: 24
        event_subtype: 
            in: 60
            out: 24
        src_type11: 
            in: 86
            out: 24
        src_type12: 
            in: 350
            out: 24
        dst_type11: 
            in: 85
            out: 24
        dst_type12: 
            in: 418
            out: 24
        src_type22: 
            in: 91
            out: 24
        src_type32: 
            in: 92
            out: 24
        amount: 
            in: 11
            out: 24
