defaults:
  - _self_
  - dataset_unsupervised/parquet_geo
  - inference/inference_agg_geo

seed_everything: 42
logger_name: geo_agg
model_path: ../models/${logger_name}.p
embed_file_name: agg_geo

pl_module:
    seq_encoder:
    _target_: ptls.nn.AggFeatureSeqEncoder
    embeddings:
      geohash_4:
        in: 10000
      geohash_5:
        in: 10000
      geohash_6:
        in: 10000
    was_logified: false
    numeric_values: {}
    log_scale_factor: 1