defaults:
  - _self_
  - dataset_unsupervised/parquet_tab_trx
  - inference/inference_trx
  - downstream/downstream

seed_everything: 42
logger_name: trx_tabgpt
model_path: ../models/${logger_name}.p
embed_file_name: ${logger_name}

data_module:
  _target_: ptls.frames.PtlsDataModule
  train_data:
    _target_: ptls.frames.gpt.GptIterableDataset
    data: ${dataset_unsupervised.train}
    max_len: 300
    min_len: 50
  valid_data:
    _target_: ptls.frames.gpt.GptIterableDataset
    data: ${dataset_unsupervised.valid}
    max_len: 300
    min_len: 50
  train_batch_size: 256
  train_num_workers: 8
  valid_batch_size: 128
  valid_num_workers: 16
  
trainer:
  gpus: 1
  auto_select_gpus: false
  max_epochs: 20
  limit_val_batches: 5000
  deterministic: true
  checkpoints_every_n_val_epochs: 1
  gradient_clip_val: 0.1
  
pl_module:
  _target_: ptls.frames.gpt.GptPretrainModule
  total_steps: 120000
  seq_encoder:
    _target_: ptls.nn.RnnEncoder
    hidden_size: 256
    input_size: 216
    num_layers: 1
    type: gru
  trx_encoder:
    _target_: ptls.nn.TrxEncoder
    norm_embeddings: false
    embeddings_noise: 0.003
    embeddings:
        event_type: 
            in: 58
            out: 24
        event_subtype: 
            in: 59
            out: 24
        src_type11: 
            in: 85
            out: 24
        src_type12: 
            in: 349
            out: 24
        dst_type11: 
            in: 84
            out: 24
        dst_type12: 
            in: 417
            out: 24
        src_type22: 
            in: 90
            out: 24
        src_type32: 
            in: 91
            out: 24
        amount: 
            in: 8
            out: 24