train:
  _target_: ptls.data_load.datasets.ParquetDataset
  data_files: 
    - scenario_mbd/data/geo/fold=0
    - scenario_mbd/data/geo/fold=1
    - scenario_mbd/data/geo/fold=2
    - scenario_mbd/data/geo/fold=3
    - scenario_mbd/data/geo/fold=4
  i_filters:
    - _target_: modules.processing.DeleteNan
      col_name: trx_event_time
    - _target_: modules.processing.DeleteNan
      col_name: dial_event_time
    - _target_: ptls.data_load.iterable_processing.SeqLenFilter
      min_seq_len: 32
    - _target_: ptls.data_load.iterable_processing.iterable_seq_len_limit.ISeqLenLimit
      max_seq_len: 4096
    - _target_: ptls.data_load.iterable_processing.feature_filter.FeatureFilter
      drop_feature_names: 
        - client_id
        - target_1
        - target_2
        - target_3
        - target_4
    - _target_: ptls.data_load.iterable_processing.CategorySizeClip
      category_max_size:
        geohash_4: 4999
        geohash_5: 4999
        geohash_6: 4999
    - _target_: ptls.data_load.iterable_processing.to_torch_tensor.ToTorch
  shuffle_files: true
valid:
  _target_: ptls.data_load.datasets.ParquetDataset
  data_files: 
    - scenario_mbd/data/geo/fold=${fold}
  i_filters:
    - _target_: modules.processing.DeleteNan
      col_name: trx_event_time
    - _target_: modules.processing.DeleteNan
      col_name: dial_event_time
    - _target_: ptls.data_load.iterable_processing.SeqLenFilter
      min_seq_len: 32
    - _target_: ptls.data_load.iterable_processing.iterable_seq_len_limit.ISeqLenLimit
      max_seq_len: 4096
    - _target_: ptls.data_load.iterable_processing.feature_filter.FeatureFilter
      drop_feature_names: 
        - client_id
        - target_1
        - target_2
        - target_3
        - target_4
    - _target_: ptls.data_load.iterable_processing.CategorySizeClip
      category_max_size:
        geohash_4: 4999
        geohash_5: 4999
        geohash_6: 4999
    - _target_: ptls.data_load.iterable_processing.to_torch_tensor.ToTorch