train:
  _target_: ptls.data_load.datasets.ParquetDataset
  data_files: 
    - scenario_datafusion/data/mm_dataset_fold/fold=0
    - scenario_datafusion/data/mm_dataset_fold/fold=1
    - scenario_datafusion/data/mm_dataset_fold/fold=2
    - scenario_datafusion/data/mm_dataset_fold/fold=3
    - scenario_datafusion/data/mm_dataset_fold/fold=4
  i_filters:
    - _target_: modules.processing.DeleteNan
      col_name: mcc_code
    - _target_: modules.processing.DeleteNan
      col_name: higher_education
    - _target_: modules.processing.TypeProc
      col_name: transaction_amt
    - _target_: modules.processing.TypeProc
      col_name: higher_education
    - _target_: ptls.data_load.iterable_processing.feature_filter.FeatureFilter
      drop_feature_names: 
        - user_id
        - cat_id
        - level_0
        - level_1
        - level_2
        - click_event_time
        - new_uid
      keep_feature_names:
        - higher_education
    - _target_: ptls.data_load.iterable_processing.SeqLenFilter
      min_seq_len: 32
    - _target_: ptls.data_load.iterable_processing.iterable_seq_len_limit.ISeqLenLimit
      max_seq_len: 4096
    - _target_: ptls.data_load.iterable_processing.category_size_clip.CategorySizeClip
      category_max_size:
        mcc_code: 349
        currency_rk: 9
    - _target_: ptls.data_load.iterable_processing.time_proc.TimeProc
      time_col: trx_event_time
    - _target_: ptls.data_load.iterable_processing.to_torch_tensor.ToTorch
    - _target_: modules.processing.TargetToTorch
      col_target: higher_education
  shuffle_files: true
valid:
  _target_: ptls.data_load.datasets.ParquetDataset
  data_files: 
    - scenario_datafusion/data/mm_dataset_fold/fold=${fold}
  i_filters:
    - _target_: modules.processing.DeleteNan
      col_name: mcc_code
    - _target_: modules.processing.DeleteNan
      col_name: higher_education
    - _target_: modules.processing.TypeProc
      col_name: transaction_amt
    - _target_: modules.processing.TypeProc
      col_name: higher_education
    - _target_: ptls.data_load.iterable_processing.feature_filter.FeatureFilter
      drop_feature_names: 
        - user_id
        - cat_id
        - level_0
        - level_1
        - level_2
        - click_event_time
        - new_uid
      keep_feature_names:
        - higher_education
    - _target_: ptls.data_load.iterable_processing.SeqLenFilter
      min_seq_len: 32
    - _target_: ptls.data_load.iterable_processing.iterable_seq_len_limit.ISeqLenLimit
      max_seq_len: 4096
    - _target_: ptls.data_load.iterable_processing.time_proc.TimeProc
      time_col: trx_event_time
    - _target_: ptls.data_load.iterable_processing.category_size_clip.CategorySizeClip
      category_max_size:
        mcc_code: 349
        currency_rk: 9
        hour: 24
        weekday: 7
    - _target_: ptls.data_load.iterable_processing.to_torch_tensor.ToTorch
    - _target_: modules.processing.TargetToTorch
      col_target: higher_education