train:
  _target_: ptls.data_load.datasets.ParquetDataset
  data_files: 
    - trx/fold=0
    - trx/fold=1
    - trx/fold=2
    - trx/fold=3
  i_filters:
    - _target_: ptls.data_load.iterable_processing.SeqLenFilter
      min_seq_len: 32
    - _target_: ptls.data_load.iterable_processing.iterable_seq_len_limit.ISeqLenLimit
      max_seq_len: 4096
    - _target_: ptls.data_load.iterable_processing.feature_filter.FeatureFilter
      drop_feature_names: 
        - client_id
        - target_1
        - target_2
        - target_3
        - target_4
    - _target_: modules.QuantilfyAmount
    - _target_: ptls.data_load.iterable_processing.CategorySizeClip
      category_max_size:
        event_type: 58
        event_subtype: 59
        src_type11: 85
        src_type12: 349
        dst_type11: 84
        dst_type12: 417
        src_type22: 90
        src_type32: 91
        amount: 10
    - _target_: ptls.data_load.iterable_processing.to_torch_tensor.ToTorch
  shuffle_files: true
valid:
  _target_: ptls.data_load.datasets.ParquetDataset
  data_files: 
    - trx/fold=4
  i_filters:
    - _target_: ptls.data_load.iterable_processing.SeqLenFilter
      min_seq_len: 32
    - _target_: ptls.data_load.iterable_processing.iterable_seq_len_limit.ISeqLenLimit
      max_seq_len: 4096
    - _target_: ptls.data_load.iterable_processing.feature_filter.FeatureFilter
      drop_feature_names: 
        - client_id
        - target_1
        - target_2
        - target_3
        - target_4
    - _target_: modules.QuantilfyAmount
    - _target_: ptls.data_load.iterable_processing.CategorySizeClip
      category_max_size:
        event_type: 58
        event_subtype: 59
        src_type11: 85
        src_type12: 349
        dst_type11: 84
        dst_type12: 417
        src_type22: 90
        src_type32: 91
        amount: 10
    - _target_: ptls.data_load.iterable_processing.to_torch_tensor.ToTorch