seq_encoder:
    _target_: ptls.nn.AggFeatureSeqEncoder
    embeddings:
      geohash_4:
        in: 10000
      geohash_5:
        in: 10000
      geohash_6:
        in: 10000
    was_logified: false
    numeric_values: {}
    log_scale_factor: 1